services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      no_cache: false
    # depends_on:
    #   - adminer
    volumes:
      - ./go/dist:/var/www/html
    ports:
      - 80:80
      - 443:443
      - 8090:8090
    restart: always
    networks:
      - network
    # profiles:
    #   - donotstart

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${MYSQL_PORT}
    volumes:
      - ./${MYSQL_STORAGE}:/var/lib/mysql
    env_file:
     - .env
    networks:
      - network
    profiles:
      - donotstart

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - ./${POSTGRES_STORAGE}:/var/lib/postgresql/data
    env_file:
     - .env
    networks:
      - network
    profiles:
      - donotstart

  zap:
    container_name: zap
    build:
      context: ./zap
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${ZAP_PORT}
    volumes:
      - ./zap/zig-linux-x86_64-0.13.0:/app/zig
      - ./zap/build:/app/build
      # - ./${FILES_STORAGE}:/var/lib/files
    restart: always
    env_file:
     - .env
    networks:
      - network
    profiles:
      - donotstart

  gin:
    container_name: gin
    build:
      context: ./gin
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${GIN_PORT}
    # depends_on:
    #   - zap
    #   - mysql
    #   - nginx
    volumes:
      - ./gin-mod-cache:/go/pkg/mod
      - ./gin/src:/app/src
      - ./${FILES_STORAGE}:${GIN_FOLDER}
    restart: always
    env_file:
     - .env
    networks:
      - network
    profiles:
      - donotstart

  go:
    container_name: go
    build:
      context: ./go
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${GO_PORT}
    volumes:
      - ./go-mod-cache:/go/pkg/mod
      - ./go:/app
    restart: always
    env_file:
     - .env
    networks:
      - network
    # profiles:
    #   - donotstart

  next:
    container_name: next
    build:
      context: ./next
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${NEXT_PORT}
      # - ${NEXT_PORT}:${NEXT_PORT}
    depends_on:
      - gin
      # - zap
    #   - nginx
    volumes:
      - ./next:/app
    restart: always
    env_file:
     - .env
    networks:
      - network
    profiles:
      - donotstart

  remix:
    container_name: remix
    build:
      context: ./remix
      dockerfile: Dockerfile
      no_cache: false
    ports:
      - ${REMIX_PORT}
      # - ${NEXT_PORT}:${NEXT_PORT}
    # depends_on:
    #   - gin
      # - zap
    #   - nginx
    volumes:
      - ./remix:/app
    restart: always
    env_file:
     - .env
    networks:
      - network
    profiles:
      - donotstart

  adminer:
    container_name: adminer
    build:
      context: ./adminer
      dockerfile: Dockerfile
      no_cache: false
    restart: always
    depends_on:
      # - mysql
      - postgres
    expose:
     - ${ADMIN_PORT}
    networks:
      - network
    profiles:
      - donotstart

networks:
  network:
    driver: bridge
